# Generated by Django 3.1 on 2024-08-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
