# Generated by Django 5.1.1 on 2024-09-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='d_ecommerce/static/images/avatars/default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
