# Generated by Django 3.1 on 2024-09-02 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cartitem_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
