# Generated by Django 3.1 on 2024-09-02 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20240902_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
